### ISSUE TITLE
Looks like the run.sh script breaks some of the .vala files if you use it before ninja

### ISSUE THREAD

**Issue by hanaral** [xchan14/readdit#3]
~~Hi, ninja fails to compile due to some of the comments having an extra slash at the end, which confuses it.~~
Edit: apperently this is entirely tied to trying to use run.sh before using ninja, I did this by mistake and caused it to add a bunch of slashes to the ends of some of the commented out lecences.

**Comment by xchan14** [comment]
I mistakenly commit the double slashes. Also, you may have to delete *.po files and re-run `ninja com.github.xchan14.readdit-pot ` and `ninja com.github.xchan14.readdit-update-po` due to renaming of package name and repository.
